Add a spinner to `ChangePasswordSceneComponent` to prevent double submit
EdgeApp/edge-login-ui-rn pull request #15
Opened 2022-08-25 03:18 UTC by itayplav

Double modal issue caused by pressing "enter" on keyboard, sending a change password request, followed by pressing "Done" which fires the second change password request. This PR prevents double submission from being possible by adding a spinner to the "Done" button.

| Airplane mode                                                                                                                                      | Pressing enter key                                                                                                                        |
|----------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------|
| <video controls width="200" src="https://user-images.githubusercontent.com/4023066/186565718-5c3cf5ec-4c8a-46f4-aa15-350eb89deea9.mp4" /> autoplay | <video controls width="200" src="https://user-images.githubusercontent.com/4023066/186565711-6258264c-fc55-4a02-b082-83a343434db7.mp4" /> |

2022-08-30 15:11 UTC, swansontec requested changes

2022-08-30 15:11 UTC, swansontec commented on src/components/scenes/ChangePasswordScene.tsx
> +  const [spinning, setSpinning] = React.useState(false)
This is a good solution, but it only applies to the change-password scene, not the other 2 versions of this scene. Instead, please put the state inside `ChangePasswordSceneComponent` itself, and then put the `setSpinning` calls before and after the calls to `onSubmit` inside `handlePress` (with try / finally).

2022-09-20 21:53 UTC, peachbits requested changes

2022-09-20 21:53 UTC, peachbits commented on src/components/scenes/ChangePasswordScene.tsx
> +      setSpinning(!spinning)
I hate to be pedantic but this should be setSpinning(false). It doesn't matter here, but in general for this pattern:

turn on activity indicator -> do some work -> turn off activity indicator 

We want to be sure to actually turn it off. In more complex code maybe `spinning` is changed in the try block or function calls within it. To be safe, when we get to the finally block we want to be 100% that the activity is turned off by setting to false.

2022-09-21 17:55 UTC, merged