Miscellaneous fixes for enabling the `strict-boolean` eslint rule
EdgeApp/edge-login-ui-rn pull request #37
Opened 2023-02-09 07:34 UTC by itayplav

2023-02-09 20:32 UTC, swansontec requested changes
This is going in the right direction, but just needs some small tweaks.

2023-02-10 05:35 UTC, itayplav commented on src/components/scenes/PinLoginScene.tsx
> +          {!this.props.userDetails.pinEnabled ? (
Done

2023-02-10 05:36 UTC, itayplav commented on src/components/common/HeaderParentButtons.tsx
> +        {appId !== null && appId !== '' && !hidePoweredBy ? (
Noted

2023-02-10 19:54 UTC, swansontec approved these changes

2023-02-10 19:54 UTC, merged