Jon/signup-security-ui-update
EdgeApp/edge-login-ui-rn pull request #50
Opened 2023-04-07 01:39 UTC by Jon-edge

1. Move permissions modal to 'Create' of new signup flow
2. Add a "YouTube" style username availability checker that fetches for username availability after some time has passed since the last keystroke.

### CHANGELOG

 none

### Dependencies

 none

### Description

 none

2023-04-10 15:59 UTC, paullinator requested changes
Added WIP fixup commit (untested) that addresses most issues in the last commit

2023-04-11 00:50 UTC, Jon-edge commented on src/common/locales/strings/enUS.json
> +  "notifications_and_refresh_permissions_branded_s": "Please enable Notifications and Background App Refreshto ensure the highest level of security for your account. %1$s will notify you if other dev
They're used in LoginInitActions c0b9252

2023-04-11 00:54 UTC, Jon-edge commented on src/components/scenes/newAccount/NewAccountUsernameScene.tsx
> +    if (isAscii(text)) setUsername(text)
This was necessary. We need to accept all ascii-valid input before we do anything else, or user input breaks since 1 character < 3 character minimum.

2023-04-11 01:10 UTC, Jon-edge commented on src/components/scenes/newAccount/NewAccountUsernameScene.tsx
> +  //    availability if the fetch was already done prior to pressing the button.
My original implementation supported this - making the next button available
before fetching, saving the user from waiting on the
AVAILABILITY_CHECK_DELAY_MS.

2023-04-11 04:01 UTC, paullinator requested changes

2023-04-11 04:01 UTC, paullinator commented on src/components/themed/OutlinedTextInput.tsx
> +              hasError
This didn't get fixed. Revert entire change to `selectionColor` back to original code which properly uses outlineTextInputTextColor

2023-04-11 04:01 UTC, paullinator commented on src/components/themed/OutlinedTextInput.tsx
> +      color: theme.iconTappable
This didn't get fixed

2023-04-11 07:56 UTC, paullinator approved these changes

2023-04-11 08:51 UTC, merged